"""Pydantic models and schema contracts for CRCA core."""

from crca_core.models.provenance import ProvenanceManifest
from crca_core.models.refusal import RefusalChecklistItem, RefusalReasonCode, RefusalResult
from crca_core.models.result import (
    AnyResult,
    BaseResult,
    CounterfactualResult,
    DiscoveryHypothesisResult,
    EstimateResult,
    IdentificationResult,
    InterventionDesignResult,
    ValidationIssue,
    ValidationReport,
)
from crca_core.models.spec import (
    AssumptionItem,
    AssumptionSpec,
    CausalGraphSpec,
    DataColumnSpec,
    DataSpec,
    DraftSpec,
    EdgeSpec,
    EntityIndexSpec,
    LockedSpec,
    NoiseSpec,
    NodeSpec,
    RoleSpec,
    SCMSpec,
    SpecStatus,
    StructuralEquationSpec,
    TimeIndexSpec,
)
from crca_core.models.validation import validate_spec

__all__ = [
    "ProvenanceManifest",
    "RefusalChecklistItem",
    "RefusalReasonCode",
    "RefusalResult",
    "AnyResult",
    "BaseResult",
    "CounterfactualResult",
    "DiscoveryHypothesisResult",
    "EstimateResult",
    "IdentificationResult",
    "InterventionDesignResult",
    "ValidationIssue",
    "ValidationReport",
    "AssumptionItem",
    "AssumptionSpec",
    "CausalGraphSpec",
    "DataColumnSpec",
    "DataSpec",
    "DraftSpec",
    "EdgeSpec",
    "EntityIndexSpec",
    "LockedSpec",
    "NoiseSpec",
    "NodeSpec",
    "RoleSpec",
    "SCMSpec",
    "SpecStatus",
    "StructuralEquationSpec",
    "TimeIndexSpec",
    "validate_spec",
]
